/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NewRouteImport } from './routes/new'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as LobbySessionIdRouteImport } from './routes/lobby.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbySessionIdRoute = LobbySessionIdRouteImport.update({
  id: '/lobby/$sessionId',
  path: '/lobby/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/join/$token': typeof JoinTokenRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/join/$token': typeof JoinTokenRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/join/$token': typeof JoinTokenRoute
  '/lobby/$sessionId': typeof LobbySessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/new' | '/join/$token' | '/lobby/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/new' | '/join/$token' | '/lobby/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/new'
    | '/join/$token'
    | '/lobby/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  JoinTokenRoute: typeof JoinTokenRoute
  LobbySessionIdRoute: typeof LobbySessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$sessionId': {
      id: '/lobby/$sessionId'
      path: '/lobby/$sessionId'
      fullPath: '/lobby/$sessionId'
      preLoaderRoute: typeof LobbySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  JoinTokenRoute: JoinTokenRoute,
  LobbySessionIdRoute: LobbySessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
